package Pong;


/**
* Pong/_ClientePongStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:44 PM CDT
*/

public class _ClientePongStub extends org.omg.CORBA.portable.ObjectImpl implements ClientePong
{

  public void actualizarTablero (int r1, int r2, int x, int y, int m1, int m2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarTablero", true);
                $out.write_long (r1);
                $out.write_long (r2);
                $out.write_long (x);
                $out.write_long (y);
                $out.write_long (m1);
                $out.write_long (m2);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                actualizarTablero (r1, r2, x, y, m1, m2        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarTablero

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Pong/ClientePong:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ClientePongStub
