package Pong;


/**
* Pong/ClientePongOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:44 PM CDT
*/

public interface ClientePongOperations 
{
  void actualizarTablero(int r1, int r2, int x, int y, int m1, int m2);
} // interface ClientePongOperations
