package Pong;


/**
* Pong/ClientePongHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:44 PM CDT
*/

abstract public class ClientePongHelper
{
  private static String  _id = "IDL:Pong/ClientePong:1.0";

  public static void insert (org.omg.CORBA.Any a, ClientePong that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClientePong extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ClientePongHelper.id (), "ClientePong");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClientePong read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientePongStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClientePong value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ClientePong narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientePong)
      return (ClientePong)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ClientePongStub stub = new _ClientePongStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ClientePong unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientePong)
      return (ClientePong)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ClientePongStub stub = new _ClientePongStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
