package Pong;

/**
* Pong/ClientePongHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:44 PM CDT
*/

public final class ClientePongHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientePong value = null;

  public ClientePongHolder ()
  {
  }

  public ClientePongHolder (ClientePong initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientePongHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientePongHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientePongHelper.type ();
  }

}
