package Pong;


/**
* Pong/ServidorPongOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:45 PM CDT
*/

public interface ServidorPongOperations 
{
  int conectar(ClientePong cliente);
  void up(int no);
  void down(int no);
} // interface ServidorPongOperations
