package Pong;


/**
* Pong/ServidorPongPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:44 PM CDT
*/

public abstract class ServidorPongPOA extends org.omg.PortableServer.Servant
 implements Pong.ServidorPongOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("conectar", new Integer (0));
    _methods.put ("up", new Integer (1));
    _methods.put ("down", new Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Pong/ServidorPong/conectar
       {
         ClientePong cliente = Pong.ClientePongHelper.read (in);
         int $result = (int)0;
         $result = this.conectar (cliente);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Pong/ServidorPong/up
       {
         int no = in.read_long ();
         this.up (no);
         out = $rh.createReply();
         break;
       }

       case 2:  // Pong/ServidorPong/down
       {
         int no = in.read_long ();
         this.down (no);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Pong/ServidorPong:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServidorPong _this() 
  {
    return ServidorPongHelper.narrow(
    super._this_object());
  }

  public ServidorPong _this(org.omg.CORBA.ORB orb) 
  {
    return ServidorPongHelper.narrow(
    super._this_object(orb));
  }


} // class ServidorPongPOA
