package Pong;

/**
* Pong/ServidorPongHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:45 PM CDT
*/

public final class ServidorPongHolder implements org.omg.CORBA.portable.Streamable
{
  public ServidorPong value = null;

  public ServidorPongHolder ()
  {
  }

  public ServidorPongHolder (ServidorPong initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServidorPongHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServidorPongHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServidorPongHelper.type ();
  }

}
