package Pong;


/**
* Pong/ServidorPong.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pong.idl
* domingo 28 de mayo de 2017 07:43:45 PM CDT
*/

public interface ServidorPong extends ServidorPongOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServidorPong
